- name: Test reading of join-command
  ansible.builtin.debug:
    msg: "kubeadm join {{lookup('ansible.builtin.file', '/tmp/qserv_tmp/join-command') }}"
    verbosity: 1
  tags:
  - kube-setup
  - kube-join

- name: Join nodes to kubernetes cluster
  become: yes
  shell:
    cmd: "{{lookup('ansible.builtin.file', '/tmp/qserv_tmp/join-command') }}"
  tags:
  - kube-setup
  - kube-join

- name: Setup qserv directory
  file:
    path: /qserv-data/default/qserv
    state: directory
  tags:
  - qserv-setup

- name: Setup ingest directory
  file:
    path: /qserv-data/default/ingest
    state: directory
  tags:
  - qserv-setup

- name: Setup replication directory
  file:
    path: /qserv-data/default/replication
    state: directory
  tags:
  - qserv-setup
