- name: Test reading of join-command
  ansible.builtin.debug:
    msg: "kubeadm join {{lookup('ansible.builtin.file', '/tmp/qserv_tmp/join-command') }}"
    verbosity: 1
  tags:
  - kube-setup
  - kube-join

- name: Join nodes to kubernetes cluster
  become: yes
  ansible.builtin.shell: "kubeadm join {{lookup('ansible.builtin.file', '/tmp/qserv_tmp/join-command') }}"
  tags:
  - kube-setup
  - kube-join
