- name: Copy setup scripts
  copy:
    src: "{{ item }}"
    dest: "/home/ubuntu/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - script1.sh
    - script2.sh

- name: Run Shell Script 1.
  shell: sh /home/ubuntu/script1.sh

- name: Run Shell Script 2.
   shell: sh /home/ubuntu/script1.sh
