# - name: Copy setup scripts
#   copy:
#     src: "{{ item }}"
#     dest: "/home/ubuntu/{{ item }}"
#     owner: ubuntu
#     group: ubuntu
#     mode: '0644'
#   loop:
#     - script1.sh
#     - script2.sh

# - name: Run Shell Script 1.
#   shell: sh /home/ubuntu/script1.sh

# - name: Run Shell Script 2.
#    shell: sh /home/ubuntu/script1.sh

- name: Copy containerd.conf to hosts
  become: yes
  template:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: Add overlay module
  become: yes
  modprobe:
    name: overlay
    state: present

- name: Add br_netfilter module
  become: yes
  modprobe:
    name: br_netfilter
    state: present

- name: Copy 99-kubernetes-cri.conf to hosts
  become: yes
  template:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: sysctl read values from all system directories
  become: yes
  shell: sysctl --system

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600