- hosts: goons
  tasks:

    - name: create new ext4 primary partition for qserv data
      community.general.parted:
        device: /dev/vdb
        label: gpt
        flags: [ lvm ]
        number: 1
        state: present
        fs_type: ext4
      become: yes
      tags:
      - tagsfs
    - name: format qserv-data partition  
      filesystem:
        fstype: ext4
        dev: /dev/vdb1
      become: yes
      tags:
      - tagsfs
    - name: mount vdb1 as qserv-data 
      mount:
        path: /qserv-data
        src: /dev/vdb1
        fstype: ext4
        state: mounted 
      become: yes
      tags:
      - tagsfs


- hosts: all
  roles:
    - mob_init



- hosts: boss
  roles:
    - kubernetes_boss
  tasks:
    
    - name: ssh-keygen
      community.crypto.openssh_keypair:
        path: /home/ubuntu/.ssh/jump_id_ssh_rsa
      tags:
      - ssh-setup

    - name: fetch ssh public key
      ansible.builtin.fetch:
        dest: /tmp/qserv_tmp/ssh-keys
        src: /home/ubuntu/.ssh/jump_id_ssh_rsa.pub      
        
      tags:
      - ssh-setup

- hosts: goons
  tasks:    
    - name: deploy jump host ssh key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/tmp/qserv_tmp/ssh-keys/sv-qserv-dev-jump/home/ubuntu/.ssh/jump_id_ssh_rsa.pub') }}"
      tags:
      - ssh-setup
      
  hosts: goons
  roles:
    - kubernetes_goon

- hosts: goons
  tasks:
    - name : set up root qserv-data directory
      file:
        path: /qserv-data/
        state: directory
        owner: root
        group: root
        mode: 0755
      become: yes
      tags:
        - qserv

- hosts: goons
  tasks:
    - name : set up qserv-data/default directory
      file:
        path: /qserv-data/default/
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: yes
      tags:
        - qserv

- hosts: czar:utility_nodes
  tasks:
    - name: set up ingest directory
      file:
        path: /qserv-data/default/ingest
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
      become: yes
      tags:
        - qserv 

- hosts: czar:utility_nodes
  tasks:
    - name: set up replication directory
      file:
        path: /qserv-data/default/replication
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
      become: yes
      tags:
        - qserv 

- hosts: goons
  tasks:
    - name: set up qserv directory
      file:
        path: /qserv-data/default/qserv
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
      become: yes
      tags:
        - qserv       

- hosts: jumphost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install requests python package
      pip:
        name: requests
      tags: 
        - boss
    - name: pv_copy
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/ubuntu/skateful/{{ item }}"
        mode: 0644
        owner: root
        group: root
        #overwrite: yes
      tags: 
        - d_new
        - hi 
      with_items:
        - "pvc.sh"
        - "env.sh"
          
    - name: pv_sh
      kubernetes.core.k8s:
        state: present
        src: /home/ubuntu/skateful/out/
      #remote_src: true

      
      #cmd: pvc.sh
      tags: 
        - d_new
        - boss
    - name: Sleep for 60 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 60
      tags: 
        - d_new

    - name: manifest
      become: yes
      command: bash /home/ubuntu/skateful/create-manifests.sh
      tags: 
        - hi
 

    #- name: Run kubectl get pods
    # k8s:
    # api_version: v1
    # kind: Command
    # namespace: default
    # command: kubectl apply -n default -f /home/ubuntu/skateful/out/
    # tags:
    #   - hi
    #   - boss
