- hosts: all
  roles:
    - mob_init



- hosts: boss
  roles:
    - kubernetes_boss
  tasks:
    
    - name: ssh-keygen
      community.crypto.openssh_keypair:
        path: /home/ubuntu/.ssh/jump_id_ssh_rsa
      tags:
      - ssh-setup

    - name: fetch ssh public key
      ansible.builtin.fetch:
        src: /home/ubuntu/.ssh/jump_id_ssh_rsa.pub
        dest: /tmp/qserv_tmp/ssh-keys
      tags:
      - ssh-setup

- hosts: goons
  tasks:
    
    - name: deploy jump host ssh key
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/tmp/qserv_tmp/ssh-keys/gb-qserv2-jump/home/ubuntu/.ssh/jump_id_ssh_rsa.pub') }}"
      tags:
      - ssh-setup

- hosts: goons
  roles:
    - kubernetes_goon

- hosts: goons
  tasks:
    - name : set up root qserv-data directory
      file:
        path: /qserv-data/
        state: directory
        owner: root
        group: root
        mode: 0755
      become: yes
      tags:
        - qserv

- hosts: goons
  tasks:
    - name : set up qserv-data/default directory
      file:
        path: /qserv-data/default/
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: yes
      tags:
        - qserv

- hosts: czar
  tasks:
    - name: set up ingest directory
      file:
        path: /qserv-data/default/ingest
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: yes
      tags:
        - qserv 

- hosts: czar
  tasks:
    - name: set up replication directory
      file:
        path: /qserv-data/default/replication
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: yes
      tags:
        - qserv 

- hosts: goons
  tasks:
    - name: set up qserv directory
      file:
        path: /qserv-data/default/qserv
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: yes
      tags:
        - qserv        
