- hosts: all
  roles:
    - mob_init

- hosts: boss
  roles:
    - kubernetes_boss
  tasks:
    - name: Setjoin command as fact
      ansible.builtin.set_fact:
        join_command_fact: "{{ join_command.stdout_lines[0] }}"
        cacheable: yes
      tags:
      - kube-setup

    - name: Display all variables/facts known for a host
      debug:
        var: join_command_fact
      tags:
      - kube-setup


    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
      tags:
      - kube-setup  

    - name: Get uptime information
      shell: 
        cmd: |
          /usr/bin/uptime
      register: result
      tags:
      - kube-setup

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result
      tags:
      - kube-setup


- hosts: goons
  roles:
    - kubernetes_goon
