- hosts: goons
  tasks:
    - name: create new ext4 primary partition for qserv data
      community.general.parted:
        device: /dev/vdb
        label: gpt
        flags: [ lvm ]
        number: 1
        state: present
        fs_type: ext4
      become: yes
      tags:
      - tagsfs
    - name: format qserv-data partition  
      filesystem:
        fstype: ext4
        dev: /dev/vdb1
      become: yes
      tags:
      - tagsfs
    - name: mount vdb1 as qserv-data 
      mount:
        path: /qserv-data
        src: /dev/vdb1
        fstype: ext4
        state: mounted 
      become: yes
      tags:
      - tagsfs


- hosts: all
  roles:
    - mob_init



- hosts: boss
  roles:
    - kubernetes_boss
  tasks:
    
    - name: ssh-keygen
      community.crypto.openssh_keypair:
        path: /home/ubuntu/.ssh/jump_id_ssh_rsa
      tags:
      - ssh-setup

    - name: fetch ssh public key
      ansible.builtin.fetch:
        dest: /tmp/qserv_tmp/ssh-keys
        src: /home/ubuntu/.ssh/jump_id_ssh_rsa.pub      
        #src: /tmp/qserv_tmp/ssh-keys/sv-qserv-dev-jump/home/ubuntu/.ssh/jump_id_ssh_rsa.pub
        
      tags:
      - ssh-setup

- hosts: goons
  tasks:
    
    - name: deploy jump host ssh key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/tmp/qserv_tmp/ssh-keys/sv-qserv-dev-jump/home/ubuntu/.ssh/jump_id_ssh_rsa.pub') }}"
        #key: "{{ lookup('file', '/tmp/qserv_tmp/ssh-keys/sv-qserv-jump/home/ubuntu/.ssh/jump_id_ssh_rsa.pub') }}"
      tags:
      - ssh-setup
      
  hosts: goons
  roles:
    - kubernetes_goon

- hosts: goons
  tasks:
    - name : set up root qserv-data directory
      file:
        path: /qserv-data/
        state: directory
        owner: root
        group: root
        mode: 0755
      become: yes
      tags:
        - qserv

- hosts: goons
  tasks:
    - name : set up qserv-data/default directory
      file:
        path: /qserv-data/default/
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755
      become: yes
      tags:
        - qserv

- hosts: czar:utility_nodes
  tasks:
    - name: set up ingest directory
      file:
        path: /qserv-data/default/ingest
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
      become: yes
      tags:
        - qserv 

- hosts: czar:utility_nodes
  tasks:
    - name: set up replication directory
      file:
        path: /qserv-data/default/replication
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
      become: yes
      tags:
        - qserv 

- hosts: goons
  tasks:
    - name: set up qserv directory
      file:
        path: /qserv-data/default/qserv
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
      become: yes
      tags:
        - qserv        
