- name: kubeadm init
  become: yes
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket /run/cri-dockerd.sock --upload-certs"
  args:
    creates: /etc/kubernetes/admin.conf
  async: 240
  poll: 20
  register: init_output
  tags:
  - kube-setup

- name: print init_output
  debug:
    var: init_output
  tags:
  - kube-setup

- name: create /home/ubuntu/.kube
  become: yes
  file: 
    path: /home/ubuntu/.kube
    state: directory
  tags:
  - kube-setup

- name: copy kubernetes admin.conf
  become: yes
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
  tags:
  - kube-setup

#- name: delay
#  wait_for:
#    timeout: 60
#  delegate_to: localhost
#  tags:
#  - kube-setup

- name: kubeadm network setup
  shell: 
    cmd: |
      kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  async: 240
  poll: 30
  tags:
  - kube-setup

- name: Generate join command
  shell: 
    cmd: |
      kubeadm token create --print-join-command
  register: join_command
  tags:
  - kube-setup
  - kube-join

- name: Setjoin command as fact
  ansible.builtin.set_fact:
    join_command_fact: "{{ join_command.stdout_lines[0] }} --cri-socket /var/run/cri-dockerd.sock"
    cacheable: yes
    delegate_to: boss
  tags:
  - kube-setup
  - kube-join

- name: Display join_command_fact
  debug: 
    var: join_command_fact
    verbosity: 1
  tags:
  - kube-setup
  - kube-join

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }} --cri-socket /var/run/cri-dockerd.sock" dest="/tmp/qserv_tmp/join-command"
  tags:
  - kube-setup  
  - kube-join

- name: Deploy cert manager
  shell:
    cmd: |
      kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
  tags:
  - cert-manager
  - kube-setup

- name: Check if Skateful clone exists
  stat:
    path: /home/ubuntu/skateful
  register: skateful_stat
  tags:
  - skateful

- name: Clone Skateful repository
  git:
    repo: https://github.com/k8s-school/skateful.git
    dest: /home/ubuntu/skateful
    clone: yes
    update: yes
  when: not skateful_stat.stat.exists
  tags:
  - skateful

- name: Copy skateful env.sh to clone location
  copy:
    src: env.sh
    dest: /home/ubuntu/skateful/env.sh
  tags:
  - skateful
