- name: kubeadm init
  become: yes
  shell: "kubeadm init"
  register: init_output
  tags:
  - kube-setup

- name: create /home/ubuntu/.kube
  become: yes
  file: 
    path: /home/ubuntu/.kube
    state: directory
  tags:
  - kube-setup

- name: copy kubernetes admin.conf
  become: yes
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
  tags:
  - kube-setup

- name: kubeadm network setup
  shell: 'kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"'
  tags:
  - kube-setup