- name: kubeadm init
  become: yes
  shell: kubeadm init
  register: init_output
  until: init_output.stdout.find("Your Kubernetes master has initialized successfully!") != -1
  tags:
  - kube-setup

  