apiVersion: qserv.lsst.org/v1beta1
kind: Qserv
metadata:
  name: qserv
spec:
  storage: "100Gi"
  czar:
    storage: "5Ti"
  worker:
    storage: "10Ti"
    replicas: 3
  ingest:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - 'utility'
  queryService:
      type: NodePort
      nodePort: 30040
  replication:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - sv-qserv-utility-1

  xrootd:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - 'utility'
